#!/bin/sh

if [ ! -f $1 ]; then
    echo "Missing source file"
    exit 1;
fi

if [ ! -f $2 ]; then
    echo "Missing target file"
    exit 1;
fi

SOURCE_DIR=$(dirname "$1")
TARGET_DIR=$(dirname "$2")
SOURCE_FILE=$(basename "$1")
TARGET_FILE=$(basename "$2")

docker run -v $SOURCE_DIR:/source_schema -v $TARGET_DIR:/target_schema luciditysoftware/mariadbdiff $SOURCE_FILE $TARGET_FILE
